{
 "title": "VMware vSphere - Aria Ops 2",
 "description": "VMware vSphere Dashboard (Grafana 9.x / InfluxDB v2.0)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Interval",
    "query": "5m, 30m, 1h, 6h, 12h, 24h, 7d, 30d"
   },
   {
    "name": "vcenter",
    "query": {
     "query": "resource(`VMWARE:VMwareAdapter Instance`).all().metrics(cpu|demandmhz)"
    }
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": {
     "query": "resource(VMWARE:ClusterComputeResource).whereProperties(summary|parentVcenter = \"${vcenter}\")"
    }
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": {
     "query": "resource(VMWARE:HostSystem).whereProperties(summary|parentCluster = \"${clustername}\" and summary|parentVcenter = \"${vcenter}\")"
    }
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": {
     "query": "resource(VMWARE:Datastore).whereProperties(summary|parentVcenter = \"${vcenter}\")"
    }
   },
   {
    "name": "virtualmachine",
    "label": "VM",
    "query": {
     "query": "resource(VMWARE:VirtualMachine).whereProperties(summary|parentHost = \"${esxi}\" and summary|parentCluster = \"${clustername}\" and summary|parentVcenter = \"${vcenter}\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Datacenter Overview - vCenter = ${vcenter}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "vSphere Overview",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datacenter).all().metrics(cpu|demandmhz).count()"
    },
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).all().metrics(cpu|demandmhz).count()"
    },
    {
     "queryText": "resource(VMWARE:HostSystem).name(\"${esxi}\").metrics(cpu|demandmhz).count()"
    },
    {
     "queryText": "resource(VMWARE:VirtualMachine).whereProperties(summary|parentHost = \"${esxi}\").metrics(cpu|demandmhz).count()"
    }
   ]
  },
  {
   "title": "Cluster Overview - vCenter = ${vcenter}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$clustername - CPU Overprovisioning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "repeat": "clustername",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(cpu|corecount_provisioned)"
    },
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(cpu|vcpus_allocated_on_all_vms)"
    },
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(cpu|vcpus_to_cores_allocation_ratio)"
    }
   ]
  },
  {
   "title": "$clustername - Memory Overprovisioning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "repeat": "clustername",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(mem|host_usable)"
    },
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(mem|memory_allocated_on_all_vms)"
    },
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(mem|virtual_to_physical_memory_allocation_ratio)"
    }
   ]
  },
  {
   "title": "Overprovisioned",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Cluster Status - vCenter = ${vcenter}, Cluster = ${clustername}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(cpu|demandPct)"
    }
   ]
  },
  {
   "title": "Cluster RAM Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(mem|usage_average)"
    }
   ]
  },
  {
   "title": "Datastores - Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datastore).all().metrics(diskspace|total|workload)"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(net:physical|received_average, net:physical|transmitted_average)"
    }
   ]
  },
  {
   "title": "Cluster Storage Adapter",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:ClusterComputeResource).name(\"${clustername}\").metrics(disk|write_average, disk|read_average)"
    }
   ]
  },
  {
   "title": "Datastore Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$datastore",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "repeat": "datastore",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "resource(VMWARE:Datastore).all().metrics(diskspace|total|workload)"
    }
   ]
  },
  {
   "title": "Hypervisor Status - vCenter = ${vcenter}, Cluster = ${clustername}, Hypervisor = ${esxi}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hypervisor CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:HostSystem).name(\"${esxi}\").metrics(cpu|demandPct)"
    }
   ]
  },
  {
   "title": "Hypervisor Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:HostSystem).name(\"${esxi}\").metrics(mem|host_usagePct)"
    }
   ]
  },
  {
   "title": "Hypervisor Net Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:HostSystem).name(\"${esxi}\").metrics(net|usage_capacity)"
    }
   ]
  },
  {
   "title": "vCenter CPU/RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "resource(`VMWARE:VMwareAdapter Instance`).all().metrics(cpu|capacity_usagepct_average, mem|host_usagePct)"
    }
   ]
  },
  {
   "title": "Virtual Machine Status - VM = ${virtualmachine}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Machine CPU Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"${virtualmachine}\").metrics(cpu|demandPct)"
    }
   ]
  },
  {
   "title": "Virtual Machine Memory Usage Avg.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"${virtualmachine}\").metrics(mem|consumedPct)"
    }
   ]
  },
  {
   "title": "Virtual Machine CPU READY ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"${virtualmachine}\").metrics(cpu|demandmhz)"
    }
   ]
  },
  {
   "title": "Virtual Machine Network Usage Avg (Kbps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"${virtualmachine}\").metrics(net|usage_average)"
    }
   ]
  },
  {
   "title": "Virtual Machine Disk Performance (Read VMFS Block IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"${virtualmachine}\").metrics(virtualDisk|numberWriteAveraged_average)"
    }
   ]
  },
  {
   "title": "Virtual Machine Disk Performance (Write VMFS Block IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"${virtualmachine}\").metrics(virtualDisk|numberReadAveraged_average)"
    }
   ]
  },
  {
   "title": "Virtual Machine Disk Performance (Block Latency Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "queryText": "resource(VMWARE:VirtualMachine).name(\"${virtualmachine}\").metrics(virtualDisk|totalLatency)"
    }
   ]
  }
 ]
}